#ifndef PRACTPROJ_COLORS_H
#define PRACTPROJ_COLORS_H

#define CMD_COLOR_BLACK '0'
#define CMD_COLOR_BLUE '1'
#define CMD_COLOR_GREEN '2'
#define CMD_COLOR_LBLUE '3'
#define CMD_COLOR_RED '4'
#define CMD_COLOR_PURPLE '5'
#define CMD_COLOR_YELLOW '6'
#define CMD_COLOR_WHITE '7'
#define CMD_COLOR_GREY '8'
#define CMD_COLOR_LBLUE '9'
#define CMD_COLOR_LGREEN 'A'
#define CMD_COLOR_LLBLUE 'B'
#define CMD_COLOR_LRED 'C'
#define CMD_COLOR_LPURPLE 'D'
#define CMD_COLOR_LYELLOW 'E'
#define CMD_COLOR_LWHITE 'F'

#define ESC_COLOR_FG_BLACK 30
#define ESC_COLOR_FG_RED 31
#define ESC_COLOR_FG_GREEN 32
#define ESC_COLOR_FG_YELLOW 33
#define ESC_COLOR_FG_BLUE 34
#define ESC_COLOR_FG_PURPLE 35
#define ESC_COLOR_FG_LBLUE 36
#define ESC_COLOR_FG_WHITE 37

#define ESC_COLOR_BG_BLACK 40
#define ESC_COLOR_BG_RED 41
#define ESC_COLOR_BG_GREEN 42
#define ESC_COLOR_BG_YELLOW 43
#define ESC_COLOR_BG_BLUE 44
#define ESC_COLOR_BG_PURPLE 45
#define ESC_COLOR_BG_LBLUE 46
#define ESC_COLOR_BG_WHITE 47

#define ESC_STYLE_UNDERLINED 4

#endif //PRACTPROJ_COLORS_H
